#!/bin/bash
UNIQUE_EXPR_ID=1
PATH_TO_DATA_DIR=/data2/users/fz920/NVAE/data
PATH_TO_CODE_DIR=/data2/users/fz920/NVAE
PATH_TO_CHECKPOINT_DIR=/data2/users/fz920/NVAE/checkpoint
export EXPR_ID=UNIQUE_EXPR_ID
export DATA_DIR=PATH_TO_DATA_DIR
export CHECKPOINT_DIR=PATH_TO_CHECKPOINT_DIR
export CODE_DIR=PATH_TO_CODE_DIR
